#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    i = 0
    lo = 0
    hi = 0
    while i < len(arr):
      total = 0
      
      for j in range(len(arr)):
        if j != i:
            total += arr[j]
            
      if i == 0:
        lo = hi = total
      elif total < lo:
        lo = total
      elif total > hi:
        hi = total
        
      i += 1;
      
    print(lo, hi)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
