#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos = 0
    neg = 0 
    zero = 0
    for num in arr:
        if num == 0:
            zero += 1
        elif num >= 0:
            pos += 1
        else:
            neg += 1
            
    print(format(pos/len(arr), f".{6}f"))
    print(format(neg/len(arr), f".{6}f"))
    print(format(zero/len(arr), f".{6}f"))
            
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
