#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    if s[8] == 'A':
        new = s[0:8]
        hour = int(new[0:2])
        if hour == 12:
          return '00' + new[2:]
        else:
          return new 
    else:
        new = s[0:8]
        hour = int(new[0:2])
        if hour == 12:
            return new
        else:
            hour += 12
            return str(hour) + new[2:]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
